name: Tests 

on: [workflow_call]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/.cache/pytest
          key: ${{ runner.os }}-poetry-tests-${{ hashFiles('poetry.lock') }}
      - name: Install project
        run: poetry install --no-interaction --sync --with=nox,test
      - name: Run unit tests on Python ${{ matrix.python-version }}
        run: poetry run nox --no-venv --no-install --non-interactive -s tests -- -vv
